stages: [build, docker]

build:
  stage: build
  image: rust:1.79
  script:
    - rustc --version
    - cargo build --release
  artifacts:
    paths:
      - target/release/ddui

docker:
  stage: docker
  image: docker:25
  services: [docker:25-dind]
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  rules:
    - if: $CI_COMMIT_BRANCH
